name: kevin_ecomly
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  get_it: ^8.2.0
  go_router: ^16.3.0
  lottie: ^3.3.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/

  fonts:
    - family: Switzer
      fonts:
        - asset: assets/fonts/Switzer/Switzer-Black.otf
        - asset: assets/fonts/Switzer/Switzer-BlackItalic.otf
          style: italic
        - asset: assets/fonts/Switzer/Switzer-Bold.otf
        - asset: assets/fonts/Switzer/Switzer-BoldItalic.otf
          style: italic
        - asset: assets/fonts/Switzer/Switzer-Extrabold.otf
        - asset: assets/fonts/Switzer/Switzer-ExtraboldItalic.otf
          style: italic
        - asset: assets/fonts/Switzer/Switzer-Extralight.otf
        - asset: assets/fonts/Switzer/Switzer-ExtralightItalic.otf
          style: italic
        - asset: assets/fonts/Switzer/Switzer-Italic.otf
          style: italic
        - asset: assets/fonts/Switzer/Switzer-Light.otf
        - asset: assets/fonts/Switzer/Switzer-LightItalic.otf
          style: italic
        - asset: assets/fonts/Switzer/Switzer-Medium.otf
        - asset: assets/fonts/Switzer/Switzer-MediumItalic.otf
          style: italic
        - asset: assets/fonts/Switzer/Switzer-Regular.otf
        - asset: assets/fonts/Switzer/Switzer-Semibold.otf
        - asset: assets/fonts/Switzer/Switzer-SemiboldItalic.otf
          style: italic
        - asset: assets/fonts/Switzer/Switzer-Thin.otf
        - asset: assets/fonts/Switzer/Switzer-ThinItalic.otf
          style: italic
